### ISSUE TITLE
Run mod

### ISSUE THREAD

**Issue by BlesseNtumble** [EternalBlueFlame/Traincraft-5#13]
Good afternoon.
I tried to do build your port, but got some errors when launch mod:

java.lang.NoClassDefFoundError: src/train/common/items/ItemWrench

java.lang.NoClassDefFoundError: src/train/common/tile/TileWaterWheel 
at src.train.common.blocks.TCBlocks.loadBlocks(TCBlocks.java:42) ~[TCBlocks.class:?] 
at src.train.common.blocks.TCBlocks.init(TCBlocks.java:20) ~[TCBlocks.class:?] 
at src.train.common.Traincraft.preInit(Traincraft.java:85) ~[Traincraft.class:?]

How do I make a normal build?
I use your build.gradle. Just has added import library

**Comment by EternalBlueFlame** [comment]
These errors are due to improper importation of the mod's dependencies (Buildcraft, ic2, etc).
add the lib folder to your project's dependencies and that should resolve the issue.

**Comment by BlesseNtumble** [comment]
I have a library in folder "lib", but errors are still there.

**Comment by EternalBlueFlame** [comment]
here is a better example of what I meant.
http://i.imgur.com/Wid6EOq.png

if this is not the problem then the issue is probably related to improper setup of the source.
Intelij:
gradlew setupDecompWorkspace --refresh-dependencies
gradlew idea

eclipse:
gradlew setupDecompWorkspace --refresh-dependencies
gradlew eclipse

**Comment by BlesseNtumble** [comment]
For some reason buildcraft not see ....
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench

**Comment by BlesseNtumble** [comment]
I found the cause. The port does not work without Buildcraft
