### ISSUE TITLE
Cart and Locomotive Locking and Protection

### ISSUE THREAD

**Issue by Czarified** [EternalBlueFlame/Traincraft-5#147]
Currently, there is a button in the gui to "Lock" your rolling stock. If I lock my rolling stock (even as an OP in creative, or otherwise), others can come up to it, right-click, and cannot access it. However, if they click a second time, they can access the inventory, destroy the rolling stock, or attach the rolling stock to their own locomotive and haul it away.

I don't know what the original intention was for this feature, but currently it doesn't really protect anything, it only seems to be that way.

Note: During testing we had FTB Utilities installed for land claims, but it didn't seem to matter where the rolling was or was placed, to repeat this behavior.

**Comment by EternalBlueFlame** [comment]
This was a bug in revision 2 and older, get the latest revision (3) which was released today and let us know if it's still a problem.

**Comment by Czarified** [comment]
We'll install it and test it out! Will report back.

**Comment by NitroxydeX** [comment]
@Czarified and? Works now?

**Comment by Czarified** [comment]
Sorry for the delay, we just got back. The issue is not resolved. It seems to operate exactly the same way. It gives you the chat message "This train is locked." then if you right click again, you have full access to the inventory.

Server and clients were all updated.

**Comment by NitroxydeX** [comment]
@Czarified can you give more informations about the whole environment? Which Server-Software is used? (Forge, Cauldron, KCauldron, Thermos....) and so on.

**Comment by Czarified** [comment]
I will list the mods I think are important below.
- Forge 10.13.4.1614
- Traincraft release from 9/11
- Railcraft 9.12.2.0
- FTBUtilities-1.7.10-1.0.18.3
- FTBLib-1.7.10-1.0.18.3

**Comment by EternalBlueFlame** [comment]
Well even if the inventory is still accessible, what about the controls? That's mainly what was supposed to have been fixed last patch.

**Comment by NitroxydeX** [comment]
Well. He talks about the Freight Cars mainly.. they are working for me. Can you give more informations what Freight Car you are referring to?

**Comment by Czarified** [comment]
We just logged on to check. Bug still exists, and the cart did not update for the other player until a relog. We were all de-opped and in survival mode. The Box Cart (US) (#4453).
