### ISSUE TITLE
constant crashes by diesel locomotives

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#438]
Hey guys, I have a huge and annoying problem...This problem exists already since we are using Traincraft in our modpack (015 I think). At any random time, the server crashes caused by a random diesel loco anywhere in the world. Until we remove this loco its everytime the same loco causing the crashes. Next time it is another until destroyed and so on and so on. I really don't the any reason for that and hope you can help me addressing the issue. For any other information, just ask!

greetings, xNccPlay

[crash-2018-12-12_18.05.59-server.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/2673098/crash-2018-12-12_18.05.59-server.txt)
[crash-2018-12-12_19.27.39-server.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/2673099/crash-2018-12-12_19.27.39-server.txt)

**Comment by EternalBlueFlame** [comment]
015 is 3 versions out of date, this bug is already fixed in newer releases.

**Comment by EternalBlueFlame** [comment]
I should note, you can _sorta_ fix this bug by enabling "Remove Erroring Entities" in your forge.cfg file of your configs folder.
When the error occurs the entity will just get deleted rather than crashing the server. Not a good fix, but it works if for whatever reason you can't update.

**Comment by xNccPlay** [comment]
Oh I forgot to say, that this problem still exists for us with 017. We can't update to 018 cause we are using auto driving trains and with unlimited speed? Uhh, that will not work :D

**Comment by EternalBlueFlame** [comment]
Interesting, that problem probably got fixed in 018 then, i know it was fixed in one of them...
at any rate, you can _sorta_ fix it with the forge.cfg thing i mentioned before.
019 will be out sometime later this month with a number of fixed things from 018, including the speed bug.

**Comment by xNccPlay** [comment]
Okay I'll try it with the config change you noticed. And yes, I can't wait for 019 :D
