### ISSUE TITLE
Fails to compile , May 29 , 19

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#477]
Tried to compile today , errors with weird punctuation issues
OS -  Windows 10 x64 build 1903 also tested on Linux Mint with same result
Opensdk Java 8 and Oricle Java sdk  x64 build 212

D:\dev\tc>gradlew setupDecompWorkspace --refresh-dependencies build

D:\dev\tc\build\sources\java\train\common\api\Locomotive.java:1703: error: ';' expected
    public void disconnectFromServer() {
                                    ^
D:\dev\tc\build\sources\java\train\common\api\Locomotive.java:1713: error: reached end of file while parsing
}
 ^
90 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8 mins 13.383 secs

**Comment by EternalBlueFlame** [comment]
Those line numbers look off.... Try re-downloading the source and doing it again, you might have some classes that aren't updated or something.

**Comment by Tsoccerguy3** [comment]
I deleted the local repo . and started fresh

C:\Users\ASUS>cd dev

C:\Users\ASUS\Dev>git clone https://github.com/EternalBlueFlame/Traincraft-5.git tc
Cloning into 'tc'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 21575 (delta 0), reused 4 (delta 0), pack-reused 21567
Receiving objects: 100% (21575/21575), 81.86 MiB | 8.42 MiB/s, done.
Resolving deltas: 100% (12820/12820), done.
Checking out files: 100% (2340/2340), done.

C:\Users\ASUS\Dev>cd tc

C:\Users\ASUS\Dev\tc>gradlew setupDecompWorkspace --refresh-dependencies build

C:\Users\ASUS\Dev\tc\build\sources\java\train\common\api\Locomotive.java:1703: error: ';' expected
    public void disconnectFromServer() {
                                    ^
C:\Users\ASUS\Dev\tc\build\sources\java\train\common\api\Locomotive.java:1713: error: reached end of file while parsing
}
 ^
90 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 49.783 secs

**Comment by EternalBlueFlame** [comment]
Well the error shows there's a missing semicolon at the end of 595 of the locomotive class, but that's not an issue with the source on git.

https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/Locomotive.java#L595

I'm thinking it might either be an issue with your git, or maybe your OS localization, one thing you can try is copying that class manually, or downloading the entire project manually as a zip, then extracting it and doing all the setup stuff from there.

**Comment by Tsoccerguy3** [comment]
I , git checkout 8c1f0dcb452e4fb8ec85d2e851886fe40a431a71
and built from that with no problem . I think KennyPeachKing added some extra punctuation in the newest commits . I compiled from the Command Prompt . Your IDE which ever it is is smart enough to remove a extra bracket or semicolon . compiling from the command prompt , it is what it is and fails

**Comment by Tsoccerguy3** [comment]
The compiled mod from that commit crashes on world load

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 29/05/19 9:07 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at train.common.entity.rollingStock.EntityPassenger7.func_70043_V(EntityPassenger7.java:29)
	at train.common.api.EntityRollingStock.moveOnTCSlope(EntityRollingStock.java:1360)
	at train.common.api.EntityRollingStock.updateOnTrack(EntityRollingStock.java:1181)
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:805)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at train.common.entity.rollingStock.EntityPassenger7.func_70043_V(EntityPassenger7.java:29)
	at train.common.api.EntityRollingStock.moveOnTCSlope(EntityRollingStock.java:1360)
	at train.common.api.EntityRollingStock.updateOnTrack(EntityRollingStock.java:1181)
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:805)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: tc.Passenger Short Green (train.common.entity.rollingStock.EntityPassenger7)
	Entity ID: 182
	Entity Name: Passenger Car
	Entity's Exact location: 254.77, 70.65, 159.50
	Entity's Block location: World: (254,70,159), Chunk: (at 14,4,15 in 15,9; contains blocks 240,0,144 to 255,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.05, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Traincraft Test Track 1.7.10
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 635 Drop: 0
	Level seed: 8653760367652333124
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (257,69,186), Chunk: (at 1,4,10 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8167275 game time, 7011 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 162575 (now: false), thunder time: 70448 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 116231376 bytes (110 MB) / 352321536 bytes (336 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	tc{4.4.1_020} [Traincraft] (Traincraft-4.4.1_020.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tsoccerguy3** [comment]
looks like the recent compile is not compatible with worlds created with a older traincraft version

**Comment by EternalBlueFlame** [comment]
well it's not my IDE, because it compiles from command line fine for me, so something is different here.....

as for that crash, it's because that specific passenger car doesn't check if there's a rider before setting their position, i'll fix that now.

**Comment by EternalBlueFlame** [comment]
this may take a few minutes actually, this crash exists in almost every passenger car in the mod....

**Comment by Tsoccerguy3** [comment]
I downloaded the zip and compiled from that . I got the same results and a fail to compile . Im almost certain there is extra punctuation in the latest commit

**Comment by EternalBlueFlame** [comment]
okay yeah i found the missing brackets while i was fixing the stock, my local copy wasn't actually up to date. my mistake.
fixing it now

**Comment by EternalBlueFlame** [comment]
Forgot to ping this issue in the latest commit, but changes are pushed and all the bugs should be fixed.

**Comment by Tsoccerguy3** [comment]
yes it compiles now , but it still crashes on world load

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 29/05/19 11:09 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at train.common.entity.rollingStock.EntityCaboose3.func_70043_V(EntityCaboose3.java:28)
	at train.common.api.EntityRollingStock.moveOnTCSlope(EntityRollingStock.java:1322)
	at train.common.api.EntityRollingStock.updateOnTrack(EntityRollingStock.java:1181)
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:805)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at train.common.entity.rollingStock.EntityCaboose3.func_70043_V(EntityCaboose3.java:28)
	at train.common.api.EntityRollingStock.moveOnTCSlope(EntityRollingStock.java:1322)
	at train.common.api.EntityRollingStock.updateOnTrack(EntityRollingStock.java:1181)
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:805)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: tc.Caboose Black (train.common.entity.rollingStock.EntityCaboose3)
	Entity ID: 168
	Entity Name: Caboose
	Entity's Exact location: 246.39, 69.06, 159.50
	Entity's Block location: World: (246,69,159), Chunk: (at 6,4,15 in 15,9; contains blocks 240,0,144 to 255,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.06, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Traincraft Test Track 1.7.10
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 634 Drop: 0
	Level seed: 8653760367652333124
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (257,69,186), Chunk: (at 1,4,10 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8167277 game time, 7013 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 162573 (now: false), thunder time: 70446 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 125135496 bytes (119 MB) / 352321536 bytes (336 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	tc{4.4.1_020} [Traincraft] (Traincraft-4.4.1_020.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tsoccerguy3** [comment]
Still a problem opening an exiting map .

on a new map i see that the mod has new Hover locomotives like in back to the future . lol , I know you fix 1 bug and create another .
just to let you know


![2019-05-29_23 29 54](https://user-images.githubusercontent.com/22108822/58606542-dba96700-8269-11e9-99c8-a2548d668d29.png)

**Comment by EternalBlueFlame** [comment]
whoops, missed the cabooses when fixing the rider offsetting, i'll deal with that now.

as for the hovering trains, that probably just happened from data corruption during all the crashes.

**Comment by Tsoccerguy3** [comment]
the hovering trains , i spawned on a new map that i created just to test the newly compiled traincraft mod .
I was testing the cabooses and discovered that spawning trains on the track hovered above the track . I will delete the config files and make a new map to test on . I will let you know what happens

**Comment by Tsoccerguy3** [comment]
I re-tested on a new flat map floating steams and diesels . The trains will no longer start 
![2019-05-30_00 33 42](https://user-images.githubusercontent.com/22108822/58608732-f6340e00-8272-11e9-8be5-af94cd239247.png)

**Comment by Tsoccerguy3** [comment]
Did you want me to open a new issue with placing trains on tracks they spawn 2 blocks above the track and although you can enter them and place fuel , the train will not start?

**Comment by EternalBlueFlame** [comment]
Doesn't really matter, I'm pretty lax with this stuff.
i think the issue is for whatever reason the bogie doesn't understand the track and it derails the train a block above the track. i'll have to double over the pathfinding code to see what breaks where.
I've also got a few texture bugs and other stuff to fix while I'm in there....

**Comment by EternalBlueFlame** [comment]
Small update, the issue seems to be that the bogie doesn't spawn on server side (remember that MC is still client/server in singleplayer). so now it's a process of figuring out why it doesn't spawn...

**Comment by Tsoccerguy3** [comment]
I see you committed some fixes , here is the crash log for this compile . Game crashes on world load

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 31/05/19 10:15 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at train.common.api.EntityRollingStock.updateOnTrack(EntityRollingStock.java:1167)
	at train.common.entity.rollingStock.EntityLocoSteamForneyRed.updateOnTrack(EntityLocoSteamForneyRed.java:166)
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:801)
	at train.common.api.Locomotive.func_70071_h_(Locomotive.java:1000)
	at train.common.api.SteamTrain.func_70071_h_(SteamTrain.java:67)
	at train.common.entity.rollingStock.EntityLocoSteamForneyRed.func_70071_h_(EntityLocoSteamForneyRed.java:60)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at train.common.api.EntityRollingStock.updateOnTrack(EntityRollingStock.java:1167)
	at train.common.entity.rollingStock.EntityLocoSteamForneyRed.updateOnTrack(EntityLocoSteamForneyRed.java:166)
	at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:801)
	at train.common.api.Locomotive.func_70071_h_(Locomotive.java:1000)
	at train.common.api.SteamTrain.func_70071_h_(SteamTrain.java:67)
	at train.common.entity.rollingStock.EntityLocoSteamForneyRed.func_70071_h_(EntityLocoSteamForneyRed.java:60)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: tc.Loco Steam Forney (train.common.entity.rollingStock.EntityLocoSteamForneyRed)
	Entity ID: 84
	Entity Name: Forney (US)
	Entity's Exact location: 416.50, 74.85, 171.50
	Entity's Block location: World: (416,74,171), Chunk: (at 0,4,11 in 26,10; contains blocks 416,0,160 to 431,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Traincraft Test Track 1.7.10
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 639 Drop: 0
	Level seed: 8653760367652333124
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (257,69,186), Chunk: (at 1,4,10 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8160004 game time, 24004 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 8642 (now: true), thunder time: 8642 (now: true)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 124649328 bytes (118 MB) / 352321536 bytes (336 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	tc{4.4.1_020} [Traincraft] (Traincraft-4.4.1_020.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tsoccerguy3** [comment]
These are moving trains
![2019-05-31_15 50 38](https://user-images.githubusercontent.com/22108822/58731718-8da57800-83bd-11e9-82df-fc92106c6356.png)
![2019-05-31_15 50 54](https://user-images.githubusercontent.com/22108822/58731719-8da57800-83bd-11e9-8be1-dab7571f797a.png)

Still crashing on existing worlds on world load .
Further testing , no crash on a new world in single player

Path finding for trains is broken , the front of the train will stay in the direction it is placed on the track .
can not link trains to any cars .

this is what i found so far

**Comment by EternalBlueFlame** [comment]
alright, i think it should all be good now...?

**Comment by Tsoccerguy3** [comment]
All fixed , thx , closed
